### ISSUE TITLE
Android support library version should be 24.0.0

### ISSUE THREAD

**Issue by janheinrichmerker** [orhanobut/versionist#17]

**Comment by janheinrichmerker** [comment]
Maybe it would be better to fetch the latest version from https://developer.android.com/topic/libraries/support-library/revisions.html instead of https://developer.android.com/topic/libraries/support-library/features.html . It seems that the versions on https://developer.android.com/topic/libraries/support-library/features.html are not always up to date.

**Comment by orhanobut** [comment]
Thanks, I'll update it! Pull request is also very welcome

**Comment by orhanobut** [comment]
Fixed it. It will fetch latest versions now.
